server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: line-bullydb

  datasource:
    url: jdbc:h2:mem:bullydb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    com.line.revenge.api: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info